version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PORT=${PORT:-3000}
        volumes:
            - .:/app
        ports:
            - "${PORT:-3000}:${PORT:-3000}"
            #- "3000:3000"
        env_file:
            - .env
        depends_on:
            - db
            - redis

    db:
        image: postgres
        restart: always
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis
        command: redis-server --requirepass ${REDIS_PASSWORD} --user ${REDIS_USER}
        restart: always
        env_file:
            - .env

volumes:
    postgres_data:
